# Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

# RoostTestHash=2c3a7f4837

config:
  target: "{{ $processEnvironment.API_HOST }}"
  processor: "./custom-processor.js"
  plugins:
    expect: {}
  payload:
    path: "./pet_petId_get_others.csv"
    fields:
      - "petId"
    skipHeader: true

scenarios:
  - name: "GET '/pet/{petId}' API Test Scenario - Failure and Edge Cases"
    flow:
      - think: 5
      - get:
          url: "/pet/{{ petId }}"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          capture:
            - json: "$"
              as: "response"
          log: "Valid payload: testing for '404 Not Found' since CSV does not contain any pet IDs that exist in the system"
      - think: 2
      - get:
          url: "/pet/invald_petId"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          capture:
            - json: "$"
              as: "response_Invalid_Id"
          log: "Invalid Id: testing for '400 Invalid ID' since we passed invalid petID"
      - think: 2
      - get:
          url: "/invalid/pet/{{ petId }}"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          capture:
            - json: "$"
              as: "response_Invalid_URL"
          log: "Invalid URL: testing for '404 Not Found' since we passed an invalid URL"
      - think: 2
      - get:
          url: "/pet/{{ petId }}"
          headers:
            Authorization: "Invalid {{$processEnvironment.AUTH_TOKEN}}"
          capture:
            - json: "$"
              as: "response_Invalid_Auth"
          log: "Invalid Auth: testing for '403 Forbidden' since we passed invalid authorization token"
      - think: 5

    afterScenario:
      - log: "Scenario execution completed"

afterAll:
      - log: "All scenarios completed execution"
